version: "3.8"

services:
  backend:
    build:
      context: ./my-backend
      dockerfile: Dockerfile
    image: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pc_shop
      - SPRING_DATASOURCE_USERNAME= root
      - SPRING_DATASOURCE_PASSWORD= 1234
    depends_on:
      - db
    networks:
      - react-spring
      - spring-mysql

  frontend:
    build:
      context: ./my-frontend
      dockerfile: Dockerfile
    image: react-app
    ports:
      - "3000:80"
    networks:
      - react-spring
    depends_on:
      - backend

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "pc_shop"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql

volumes:
  db-data:
networks:
  react-spring: {}
  spring-mysql: {}
